version: "3.7"

services:
  nuxt-app:
    build: ./nuxt-app
    container_name: nuxt-app
    restart: always
    ports:
      - "4002:4002"
    command: "npm run start"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
